---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result

- debug: var=result

- name: Delete instances
  os_server:
    name: "{{ item.id }}"
    cloud: openstack
    state: absent
  with_items: "{{result.openstack_servers}}"
