# Add the app-instances private_ip_address to the aws dynamic inventory group: apps

- hosts: tag_AnsibleGroup_apps:tag_AnsibleGroup_bastions
  gather_facts: false
  become: false
  tasks:
    - name: add app-instances private_ip_address to the inventory group apps
      shell: "tower-cli host associate --host {{ hostvars[item].network_interfaces[0].private_ip_address}} --group apps"
      #debug:
      #  msg: "{{ hostvars[item].network_interfaces[0].private_ip_address}}"
      with_items: "{{ groups.tag_AnsibleGroup_apps }}"
      delegate_to: "{{ groups.tag_AnsibleGroup_bastions[0] }}"
      become: true
      run_once: true

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: tag_AnsibleGroup_frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}
        
# Setup database tier

- name: setup database tier
  become: yes
  hosts: tag_AnsibleGroup_appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
