# Add the app-instances private_ip_address to the aws dynamic inventory group: apps

- name: add apps private ip-addresses to inventory group
  hosts: tag_AnsibleGroup_apps:tag_AnsibleGroup_bastions
  gather_facts: false
  become: false
  vars:
    # The 'tower_guid' var is set as extra-variable in the tower job-template executing this playbook
    tower_config_commands:
      - "tower-cli config host tower1.{{tower_guid}}.example.opentlc.com"
      - "tower-cli config username admin"
      - "tower-cli config password r3dh4t1!"
    tower_inventory: "Prod Three tier inventory"
    tower_group: "apps"
  tasks:
    - block:
      - name: add tower-cli config
        command: "{{ item }}"
        loop: "{{ tower_config_commands }}"
      
      - name: add aws app-instances private_ip_address as inventory hosts
        tower_host:
          name: "{{ hostvars[item].network_interfaces[0].private_ip_address}}"
          inventory: "{{ tower_inventory }}"
          state: present
          tower_host: tower1.{{tower_guid}}.example.opentlc.com
          tower_username: admin
          tower_password: r3dh4t1!
          tower_verify_ssl: no
        with_items: "{{ groups.tag_AnsibleGroup_apps }}"
 
      - name: add aws app-instances private_ip_address to the  inventory-group apps
        command: "tower-cli host associate --host {{ hostvars[item].network_interfaces[0].private_ip_address}} --group {{ tower_group }} --insecure"
        with_items: "{{ groups.tag_AnsibleGroup_apps }}"

      delegate_to: "{{ groups.tag_AnsibleGroup_bastions[0] }}"
      become: true
      run_once: true

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: tag_AnsibleGroup_frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}
        
# Setup database tier

- name: setup database tier
  become: yes
  hosts: tag_AnsibleGroup_appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
